#!/bin/sh
#IP configration

#SET BOARD IP
LOCAL_IP=192.168.1.108
#SETE MASK
NET_MASK=255.255.255.0
#GATEWAY
ROUTE_IP=192.168.1.1
#SET REMOTE IP
REMOTE_IP=192.168.1.102
#SET REMOTE PATH
REMOTE_PATH=/home/lingchun/
#SET LOCAL MOUNT PATH
MOUNT_PATH=/mnt/remote
#SET NETWORK CARD
NETWORK_CARD=eth0

#DOWN NETWORK CARD
ifconfig ${NETWORK_CARD} down
#SET MAC ADDRESS
ifconfig ${NETWORK_CARD} hw ether 12:25:34:21:65:54
#SET LOCAL IP
ifconfig ${NETWORK_CARD} ${LOCAL_IP}
#SET MASK
ifconfig ${NETWORK_CARD} netmask ${NET_MASK}
#ADD GATEWAY
route add default gw ${ROUTE_IP}
#OPEN LOCAL LOOP
ifconfig lo up
#OPEN NETWORK CARD
ifconfig ${NETWORK_CARD} up

sleep 3

ping $REMOTE_IP -c 3

if [ ! -e "$MOUNT_PATH" ] ;then
    mkdir "$MOUNT_PATH" -p
fi

#MOUNT
mount -o nolock,wsize=1024,rsize=1024 ${REMOTE_IP}:${REMOTE_PATH} ${MOUNT_PATH}

ls ${MOUNT_PATH}
